### PR TITLE
Entity IO fix for extra comma-separated values

### PR DESCRIPTION
**Pull request by dbampersand**
Fix for this issue: https://github.com/momentum-mod/lumper/issues/64

### CODE REVIEW

**Comment by tsa96** [comment]
Your branch seems to be behind the last `refactor/cleanup`, I changed this code quite significantly during review, a week or so ago.

 Sorry this is so annoying, we're fairly close to getting `refactor/cleanup` merged, just a lot of review for BIRD to do.

**Comment by dbampersand** [comment]
Oh sorry, didn't realise I was behind. I've rebased this into the most recent commit.

**Comment by tsa96** [comment]
Okay, quite busy with other areas of Momentum atm so will check this and all other PRs out once `refactor/cleanup` review is finished and I have some more time for Lumper. Feel free to PR more stuff before then, sorry for any slow reviews!

**Comment by tsa96** [comment]
This was really confusing me so I took a look at the engine code. Parsing the delay and timesToFire use `atof`/`atoi` respectively, so so they'll [ignore any subsequent non-digit chars](https://cplusplus.com/reference/cstdlib/atoi/). Loading surf_deity_ksf in debug results in a "times to fire" value of -1.

What you suggested about a tool not understanding `ESC` makes a lot of sense. I've tweaked it very slightly to throw an error if neither parse succeeds, and added some more info to the comment.

**Review by tsa96 — APPROVED** [review]

**Pull request merged**
