### PR TITLE
Texdata invalid pointer fix

### PR DESCRIPTION
**Pull request by dbampersand**
To fix this issue: https://github.com/momentum-mod/lumper/issues/51

### CODE REVIEW

**Review by tsa96 — APPROVED** [review]
Fix looks reasonable, thanks for this!

Would be a lot easier this branch was rebased straight on top of `refactor/cleanup` (and as a nit, the message should probably be fix(lib): ...`. Since there's no overlay with the auto update stuff, it's likely to make it easily cleaning up the jenga tower of commits once we start merging branches together.

**Comment by BIRD311** [comment]
DON'T MERGE THIS INTO MAIN. this includes all the refactor and updater stuff. @tsa96 don't just approve stuff :D

**Comment by tsa96** [comment]
What is wrong with approving this? Only org members have permission to merge.

**Comment by BIRD311** [comment]
@tsa96  why not target `refactor/cleanup` instead so we don't have to wait for that to get in and do rebasing (or reset -> cherrypick I guess) here afterwards because of conflicts.

**Comment by tsa96** [comment]
Yeah if we're good merging into `refactor/cleanup` that's fine

**Comment by tsa96** [comment]
Just to explain, now that `refactor/cleanup` is finally in I'm going through, rebasing your PRs on top of latest main, and merging. Sorry that this has taken so long!

**Pull request merged**
